# CI for Product Catalog Service

name: product-catalog-ci

on: 
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Go 1.22
          uses: actions/setup-go@v4
          with:
            go-version: 1.22

        - name: Build
          run: go build -o product-catalog-service src/product-catalog/main.go

        - name: Unit test
          run: go test src/prodct-catalog/...
    
    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run golangci-lint
          run: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
            golangci-lint run --timeout 5m